# Form implementation generated from reading ui file 'choice_deck.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_choice_deck_form(object):
    def setupUi(self, choice_deck_form):
        choice_deck_form.setObjectName("choice_deck_form")
        choice_deck_form.resize(1071, 341)
        choice_deck_form.setAutoFillBackground(True)
        self.nilf = QtWidgets.QPushButton(parent=choice_deck_form)
        self.nilf.setGeometry(QtCore.QRect(230, 0, 212, 341))
        self.nilf.setStyleSheet("background: rgba(255, 255, 255, 0)")
        self.nilf.setText("")
        self.nilf.setCheckable(False)
        self.nilf.setObjectName("nilf")
        self.skellege = QtWidgets.QPushButton(parent=choice_deck_form)
        self.skellege.setGeometry(QtCore.QRect(440, 0, 211, 341))
        self.skellege.setStyleSheet("background: rgba(255, 255, 255, 0)")
        self.skellege.setText("")
        self.skellege.setObjectName("skellege")
        self.skoetael = QtWidgets.QPushButton(parent=choice_deck_form)
        self.skoetael.setGeometry(QtCore.QRect(650, 0, 211, 341))
        self.skoetael.setStyleSheet("background: rgba(255, 255, 255, 0)")
        self.skoetael.setText("")
        self.skoetael.setObjectName("skoetael")
        self.kingdom_north = QtWidgets.QPushButton(parent=choice_deck_form)
        self.kingdom_north.setGeometry(QtCore.QRect(0, 0, 221, 341))
        self.kingdom_north.setStyleSheet("background: rgba(255, 255, 255, 0)")
        self.kingdom_north.setText("")
        self.kingdom_north.setObjectName("kingdom_north")
        self.monsters = QtWidgets.QPushButton(parent=choice_deck_form)
        self.monsters.setGeometry(QtCore.QRect(860, 0, 211, 341))
        self.monsters.setStyleSheet("background: rgba(255, 255, 255, 0)")
        self.monsters.setText("")
        self.monsters.setObjectName("monsters")
        self.background = QtWidgets.QLabel(parent=choice_deck_form)
        self.background.setGeometry(QtCore.QRect(0, 0, 1071, 341))
        self.background.setAutoFillBackground(True)
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap(":/newPrefix/images/decks.png"))
        self.background.setScaledContents(True)
        self.background.setObjectName("background")
        self.background.raise_()
        self.monsters.raise_()
        self.nilf.raise_()
        self.skellege.raise_()
        self.skoetael.raise_()
        self.kingdom_north.raise_()

        self.retranslateUi(choice_deck_form)
        QtCore.QMetaObject.connectSlotsByName(choice_deck_form)

    def retranslateUi(self, choice_deck_form):
        _translate = QtCore.QCoreApplication.translate
        choice_deck_form.setWindowTitle(
            _translate("choice_deck_form", "Выберите колоду")
        )


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    choice_deck_form = QtWidgets.QWidget()
    ui = Ui_choice_deck_form()
    ui.setupUi(choice_deck_form)
    choice_deck_form.show()
    sys.exit(app.exec())
